# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8590c2a5f554f607b0531ccebb95d9217f1b55b6cd456bf629f8fd56f146fcad12386b80d969b686d47e280f6b0c2b55f7e58678f5442ad5b0f90af3b7009b22

test:
  secret_key_base: cef7f31f09adf6990f840c857eef9ee1c039f4d900136d420ab8eb2377ff9c1880139c122e51367b0207df1128275b1b23871d662ea07f61eb4fa5d8053c4fde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>